### ISSUE TITLE
CNV matrix for GBM tumor cells used in Fig3C

### ISSUE THREAD

**Issue by BioAmelie** [0YuLei0/scONE-seq-data-processing#1]
@0YuLei0 
Hi Lei,

I used GSE185269_scONEseq_GBM_scWGS_normalized_counts_matrix.txt.gz to generate CNV profiles according to "DNA data analysis" in scONE-seq paper, but I can not plot similar pattern with Fig3C for GBM tumor cells. Can you share me the CNV matrix for GBM tumor cells used in Fig3C or code used on how to get CNV matrix code?

I am looking forward to hearing from you and I would appreciate it very much. 
Best regards
minfang

**Comment by 0YuLei0** [comment]
Hi - Thanks for being interested about our method. Did you try the code in "DNA_related" part in the github? 

Best,
Lei

**Comment by BioAmelie** [comment]
@0YuLei0 
Hi Lei,
I see the code in "DNA_related", and I see "Interge CNV calculation (combining counts and allele frequency)" code. In this code, it needed input "combo/combo.tsv" and "$PATH_to_barcodedcells.info.tsv". However, I only get GSE185269_scONEseq_GBM_scWGS_normalized_counts_matrix.txt and GSE185269_scONEseq_GBM_scWGS_mBAF_matrix.txt form GSE185269. Can you provide those input files?
Best regards
minfang

**Comment by BioAmelie** [comment]
@0YuLei0 
What's more, It seemed that it also need normal cells data

ginkgo_bafcnv <- baf_cnv_ginkgo(rdr = ginkgo_rdr, # normalized counts from Ginkgo
                                mbaf = ginkgo_mbaf, # mbaf from CHISEL
                                fixed_rdr = ginkgo_rdr_fixed, # **Segmentation result from "processed_counts_data**"
                                contral_baf = baf_distr, # **Median BAF across all normal cells**
                                contral_rdr = rdr_distr # **Median counts across all normal cells**
                                )

**Comment by BioAmelie** [comment]
@0YuLei0 
Hi Lei,
I used "**Interge CNV calculation (counts-based)**" code and **GSE185269_scONEseq_GBM_scWGS_normalized_counts_matrix.txt** as input, I calculated max copy number is 6, but your Fig3C max copy number is 8. So how do you calculated Fig3C CNV, do you use **Interge CNV calculation (counts-based)** or **Interge CNV calculation (combining counts and allele frequency)** ?

**Comment by 0YuLei0** [comment]
Thanks for the detailed information. I will check the file first. Regard your concerns about the copy number, it indeed needs the allele frequency to determine the right copy number. 

Best,
Lei

**Comment by BioAmelie** [comment]
@0YuLei0 
Hi Lei,

Thanks for your replay. However, I only get **GSE185269_scONEseq_GBM_scWGS_normalized_counts_matrix.txt** and **GSE185269_scONEseq_GBM_scWGS_mBAF_matrix.txt** form GSE185269, maybe it couldnot sucessfully run **Interge CNV calculation (combining counts and allele frequency)**

Best,
minfang
