### ISSUE TITLE
Using dimension reduction on scWGS data

### ISSUE THREAD

**Issue by Mashuaiii** [0YuLei0/scONE-seq-data-processing#2]
@0YuLei0 
Hi Lei,

I am very interested in your research, but I have encountered some problems. Fig3B，you use dimension reduction on scWGS data and clustered cells into four distinct genomic states. I really want to know how you do it，can you share me the code used in Fig3B ?Did you do the dimensionality reduction with GSE185269_scONEseq_GBM_scWGS_normalized_counts_matrix.txt.gz as input？

I am looking forward to hearing from you and I would appreciate it very much.
Best regards！

**Comment by 0YuLei0** [comment]
Hi, thank you for your interest in our work. We utilized a dimension reduction method in our research, which can be referenced from the following article: 10.1038/s41586-021-03357-x. We adhered to the code provided in the repository "https://github.com/navinlabcode/ACT_paper". You can explore the resource and see if it can be helpful.

**Comment by Mashuaiii** [comment]
Thank you for your prompt response！
