### ISSUE TITLE
repair.sh code

### ISSUE THREAD

**Issue by BioAmelie** [0YuLei0/scONE-seq-data-processing#3]
@0YuLei0 
Hi Lei,

In 4_RNA_UMI_quantification.sh, it need repair.sh, but I did not find on github. Could you please provide it?

Best

**Comment by dingruofan** [comment]
I'm facing the same issue

**Comment by dingruofan** [comment]
I solved this, just install BBmap, `conda install bioconda::bbmap`.

**Comment by BioAmelie** [comment]
@dingruofan 
Hi,
Cou
